import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import walletRouter from "./wallet";
import sportsRouter from "./sports";
import settleRouter from "./settle";
import betsRouter from "./bets";
import adminRouter from "./admin";
import vouchersRouter from "./vouchers";
import profileRouter from "./profile";
import withdrawalsRouter from "./withdrawals";
import apiSyncRouter from "./apiSync";
import slidesRouter from "./slides";
import betBookingsRouter from "./betBookings";
import databaseRouter from "./database";
import branchesRouter from "./branches";
import branchAdminRouter from "./branchAdmin";
import agentRouter from "./agentRoutes";
import cashUpRouter from "./cashUp";
import payoutRouter from "./payout";
import liveRouter from "./live";
import fixturesPdfRouter from "./fixturesPdf";
import pawapayRouter from "./pawapay";
import pawapaySettingsRouter from "./pawapaySettings";
import notificationsRouter from "./notifications";
import winBonusRouter from "./winBonus";
import referralRouter from "./referral";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(walletRouter);
router.use(sportsRouter);
router.use(settleRouter);
router.use(betsRouter);
router.use(adminRouter);
router.use(vouchersRouter);
router.use(profileRouter);
router.use(withdrawalsRouter);
router.use(apiSyncRouter);
router.use(slidesRouter);
router.use(betBookingsRouter);
router.use(databaseRouter);
router.use(branchesRouter);
router.use(branchAdminRouter);
router.use(agentRouter);
router.use(cashUpRouter);
router.use(payoutRouter);
router.use(liveRouter);
router.use(fixturesPdfRouter);
router.use(pawapayRouter);
router.use(pawapaySettingsRouter);
router.use(notificationsRouter);
router.use(winBonusRouter);
router.use(referralRouter);

export default router;
