-- GoWin Sportsbook – full database schema
-- Idempotent: safe to run on every container start (CREATE … IF NOT EXISTS).

SET client_min_messages = warning;

-- ── ENUM types ──────────────────────────────────────────────────────────────
DO $$ BEGIN CREATE TYPE public.bet_status       AS ENUM ('pending','won','lost','void');          EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.branch_status    AS ENUM ('active','suspended');                    EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.fixture_status   AS ENUM ('upcoming','live','finished','cancelled'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.transaction_type AS ENUM ('credit','debit','bet_placed','bet_won','bet_refund','voucher_redeem'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.user_role        AS ENUM ('user','admin','manager','branch_admin','agent','payout'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE public.user_role ADD VALUE IF NOT EXISTS 'manager'; EXCEPTION WHEN others THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.withdrawal_status AS ENUM ('pending','approved','rejected','paid'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ── Tables ───────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.settings (
    key        text NOT NULL PRIMARY KEY,
    value      text NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.sports (
    id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text    NOT NULL,
    icon text
);

CREATE TABLE IF NOT EXISTS public.branches (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       text    NOT NULL,
    code       text    NOT NULL UNIQUE,
    country    text    NOT NULL,
    city       text    NOT NULL,
    address    text    NOT NULL,
    phone      text    NOT NULL,
    email      text    NOT NULL,
    status     text    NOT NULL DEFAULT 'active',
    balance    numeric(15,2) NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.users (
    id                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username             text    NOT NULL UNIQUE,
    email                text    NOT NULL UNIQUE,
    password_hash        text    NOT NULL,
    role                 public.user_role NOT NULL DEFAULT 'user',
    public_id            integer UNIQUE,
    first_name           text,
    last_name            text,
    phone_number         text    UNIQUE,
    disabled             boolean NOT NULL DEFAULT false,
    disabled_reason      text,
    login_attempts       integer NOT NULL DEFAULT 0,
    must_change_password boolean NOT NULL DEFAULT false,
    temp_password_hash   text,
    temp_password_expiry timestamp with time zone,
    created_at           timestamp with time zone NOT NULL DEFAULT now(),
    branch_id            integer REFERENCES public.branches(id) ON DELETE SET NULL,
    commission_rate      numeric(5,2) DEFAULT 0.00
);

CREATE TABLE IF NOT EXISTS public.wallets (
    id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    balance numeric(15,2) NOT NULL DEFAULT 0.00
);

CREATE TABLE IF NOT EXISTS public.transactions (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id   integer NOT NULL REFERENCES public.wallets(id) ON DELETE CASCADE,
    amount      numeric(15,2) NOT NULL,
    type        public.transaction_type NOT NULL,
    description text    NOT NULL,
    created_at  timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.withdrawals (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    amount       numeric(15,2) NOT NULL,
    bank_details text    NOT NULL,
    status       public.withdrawal_status NOT NULL DEFAULT 'pending',
    admin_note   text,
    bet_id       integer,
    branch_id    integer,
    created_at   timestamp with time zone NOT NULL DEFAULT now(),
    updated_at   timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.password_reset_otps (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    otp_hash   text    NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    used_at    timestamp with time zone
);

CREATE TABLE IF NOT EXISTS public.vouchers (
    id                     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                   text    NOT NULL UNIQUE,
    value                  numeric(10,2) NOT NULL,
    is_redeemed            boolean NOT NULL DEFAULT false,
    redeemed_by            integer REFERENCES public.users(id) ON DELETE SET NULL,
    redeemed_at            timestamp with time zone,
    created_at             timestamp with time zone NOT NULL DEFAULT now(),
    branch_id              integer REFERENCES public.branches(id) ON DELETE SET NULL,
    allocated_to_branch    boolean NOT NULL DEFAULT false,
    allocated_to_branch_at timestamp with time zone,
    agent_id               integer REFERENCES public.users(id) ON DELETE SET NULL,
    sold_at                timestamp with time zone,
    printed_at             timestamp with time zone
);

CREATE TABLE IF NOT EXISTS public.leagues (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sport_id     integer NOT NULL REFERENCES public.sports(id) ON DELETE CASCADE,
    name         text    NOT NULL,
    external_id  text    UNIQUE,
    country_name text,
    country_key  text,
    country_logo text,
    league_logo  text
);

CREATE TABLE IF NOT EXISTS public.teams (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text NOT NULL,
    logo        text,
    external_id text UNIQUE
);

CREATE TABLE IF NOT EXISTS public.fixtures (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    league_id     integer NOT NULL REFERENCES public.leagues(id) ON DELETE CASCADE,
    home_team_id  integer NOT NULL REFERENCES public.teams(id),
    away_team_id  integer NOT NULL REFERENCES public.teams(id),
    start_time    timestamp with time zone NOT NULL,
    status        public.fixture_status NOT NULL DEFAULT 'upcoming',
    score_home    integer,
    score_away    integer,
    external_id   text UNIQUE
);

CREATE TABLE IF NOT EXISTS public.markets (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fixture_id  integer NOT NULL REFERENCES public.fixtures(id) ON DELETE CASCADE,
    market_type text    NOT NULL,
    suspended   boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS public.odds (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    market_id   integer NOT NULL REFERENCES public.markets(id) ON DELETE CASCADE,
    selection   text    NOT NULL,
    odds_value  text    NOT NULL
);

CREATE TABLE IF NOT EXISTS public.bets (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          text UNIQUE,
    user_id       integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    stake         numeric(15,2) NOT NULL,
    total_odds    numeric(10,4) NOT NULL,
    potential_win numeric(15,2) NOT NULL,
    status        public.bet_status NOT NULL DEFAULT 'pending',
    created_at    timestamp with time zone NOT NULL DEFAULT now(),
    agent_id      integer REFERENCES public.users(id) ON DELETE SET NULL,
    branch_id     integer REFERENCES public.branches(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.bet_selections (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bet_id      integer NOT NULL REFERENCES public.bets(id) ON DELETE CASCADE,
    fixture_id  integer NOT NULL REFERENCES public.fixtures(id),
    market      text    NOT NULL,
    selection   text    NOT NULL,
    odds        numeric(10,4) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.bet_bookings (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        text    NOT NULL UNIQUE,
    selections  jsonb   NOT NULL,
    created_at  timestamp with time zone NOT NULL DEFAULT now(),
    expires_at  timestamp with time zone NOT NULL DEFAULT (now() + interval '30 days')
);

CREATE TABLE IF NOT EXISTS public.slides (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename    text    NOT NULL,
    sort_order  integer NOT NULL DEFAULT 0,
    active      boolean NOT NULL DEFAULT true,
    created_at  timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.branch_float_allocations (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id    integer NOT NULL REFERENCES public.branches(id),
    agent_id     integer NOT NULL REFERENCES public.users(id),
    allocated_by integer NOT NULL REFERENCES public.users(id),
    amount       numeric(15,2) NOT NULL,
    shift_date   date    NOT NULL,
    shift_label  text    NOT NULL DEFAULT 'Day',
    status       text    NOT NULL DEFAULT 'open',
    notes        text,
    created_at   timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.cash_up_sessions (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    allocation_id   integer NOT NULL REFERENCES public.branch_float_allocations(id),
    branch_id       integer NOT NULL REFERENCES public.branches(id),
    agent_id        integer NOT NULL REFERENCES public.users(id),
    performed_by    integer NOT NULL REFERENCES public.users(id),
    opening_float   numeric(15,2) NOT NULL,
    total_bets      numeric(15,2) NOT NULL DEFAULT 0,
    total_payouts   numeric(15,2) NOT NULL DEFAULT 0,
    expected_return numeric(15,2) NOT NULL,
    cash_returned   numeric(15,2) NOT NULL,
    variance        numeric(15,2) NOT NULL,
    notes           text,
    created_at      timestamp with time zone NOT NULL DEFAULT now()
);

-- ── Default seed data ────────────────────────────────────────────────────────
INSERT INTO public.settings (key, value) VALUES
    ('site_name',          'GoWin Sportsbook'),
    ('site_currency',      'ZAR'),
    ('site_currency_symbol', 'R'),
    ('max_win',            '50000'),
    ('min_bet',            '5'),
    ('max_bet',            '10000'),
    ('max_selections',     '20'),
    ('jwt_secret',         gen_random_uuid()::text)
ON CONFLICT (key) DO NOTHING;

INSERT INTO public.sports (name, icon) VALUES ('Football', '⚽')
ON CONFLICT DO NOTHING;
